### ISSUE TITLE
CW5

### ISSUE THREAD

**Issue by ninjiaga** [oleksandrblazhko/ai204-kostetskij#22]

**Comment by ninjiaga** [comment]
![](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/oleksandrblazhko/ai204-kostetskij/laboratory-work-7/2-SoftwareDesign/2.7-PlantUML/UML-Activity.puml)
Опис тестових сценаріїв для функції Analytics.create(), створених з урахуванням WhiteBox-методів:

|FR|TestCase|Опис кроків тестового сценарію|Опис|
|:-|:-|:-|:-|
|2.2|1.1|Початкові умови: відсутня інформація що до вибраної категорії.|Виведення повідомлення, що відсутня інформація що до вибраної категорії.|
|2.2|1.2|Початкові умови: наявна інформація що до вибраної категорії.|Виведення повідомлення, що діаграму з аналітикою було успішно створено.|

**Comment by oleksandrblazhko** [comment]
рішення виконано не повністю
оцінка = 2 бали

**Comment by oleksandrblazhko** [comment]
рішення виконано не повністю
оцінка = 2 бали
