### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by ninjiaga** [oleksandrblazhko/ai204-kostetskij#3]

**Comment by ninjiaga** [comment]
Завдання 1. 
Освітленість навколишнього середовища

Доступність: у веб-мережах або інших джерелах інформації визначається , що освітленість середовище доступна у природньому та штучному вигляді (сонце, палаюче багаття, лампи, прожектори та інше).

Зрозумілість: також у більшості джерел інформації є визначення що таке освітленість навколишнього середовища (світло, сонце).

Цінність: на веб-сторінках кожний може знайти інформацію про цінність освітлення (ціна видобутку штучного світла та безкоштовна наявність природнього світла).

**Comment by ninjiaga** [comment]
Завдання 2. 

Sign up : реєстрація у додатку наближає робітника до отримання інформації щодо безпечної праці.

Сreating forms : створення форм дають адміністратору змогу зрозуміти , що робітники ознайомились із безпекою праці.

Monitoring of performance : аналітика наближує директора до розуміння активності виконаної роботи

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
